name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    # 쓰기 권한 명시적으로 부여 (에러 원인 3번 해결)
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3 # 버전 업데이트
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1 # 버전 업데이트
        env:
          # 직접 토큰을 만들 필요 없이 깃허브 기본 토큰 사용 (에러 원인 1번 해결)
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - name: Commit & Push
        run: |
          git config user.name digerati09
          git config user.email digerati09@github.com
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          # 👇 푸시하기 전에 원격 저장소의 최신 내역을 먼저 가져와 병합(rebase)하는 핵심 코드입니다.
          git pull --rebase
          git pushㅍ
