name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    # 쓰기 권한 부여
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - name: Commit & Push
        run: |
          git config user.name digerati09
          git config user.email digerati09@github.com
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          # 푸시 전 원격 저장소 변경사항 병합 (충돌 해결 핵심)
          git pull --rebase
          git push
